[package]
name = "sysy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.2.5"
libc = "0.2.31"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "z"
lto = true
strip = true
